---
base_config_path: "{{ config_path }}"
loki_config: "{{ base_config_path }}/loki"
loki_storage_dir: "{{ loki_config }}/storage"

# loki_config_directory: /etc/loki
loki_config_auth: false
# loki_config_store: /var/lib/loki
loki_config_retention: 336h
loki_config_period: 168h
# loki_config_http_address: 127.0.0.1
loki_config_http_address: 0.0.0.0
loki_config_http_port: 3100
loki_config_log_level: info

# install a containerized promtail
promtail_use_docker: false
# promtail_docker_image: "grafana/promtail:{{ loki_version }}"
promtail_config_dir: "{{ base_config_path }}/promtail"
promtail_config_directory: /etc/promtail
promtail_config_log_level: info
promtail_config_server_listen: 127.0.0.1
promtail_config_server_port: 9080
# promtail_config_client_loki_address: 127.0.0.1
promtail_config_client_loki_address: loki
promtail_config_client_loki_port: 3100
promtail_config_client_loki_path: /loki/api/v1/push
# promtail_config_client_tenant_id: luzilla
promtail_config_client_set_tenant_id: false
promtail_config_client_external_labels:
  node: "{{ inventory_hostname }}"

promtail_config_scrape_journald_path: /run/log/journal
