---
# - name: add dbs
#   community.mysql.mysql_db:
#     db:
#       - "{{ item.value.name }}"
#     state: present
#     check_implicit_admin: true
- name: Add dbs
  community.docker.docker_container_exec:
    container: mariadb
    command: mysql -u root --password={{ mysql_root_password }} -e "CREATE DATABASE IF NOT EXISTS {{ item.value.name }}";
    # argv:
    #   - mysql
    #   - -u
    #   - root
    #   - "--password={{ mysql_root_password }}"
    #   - "CREATE DATABASE IF NOT EXISTS {{ item.value.name }};"

- name: Add users for {{ item.key }}
  no_log: false
  community.docker.docker_container_exec:
    container: mariadb
    command: mysql -u root --password={{ mysql_root_password }}
      -e "CREATE USER IF NOT EXISTS {{ item.value.user }}@'{{ item.value.source | default('%', true) }}'
      IDENTIFIED BY '{{ item.value.pass }}';"
- name: Check user for {{ item.key }} - {{ item.value.user }}
  no_log: false
  community.docker.docker_container_exec:
    container: mariadb
    command: mysql -u root --password={{ mysql_root_password }}
      -e "SHOW GRANTS FOR {{ item.value.user }}@'{{ item.value.source | default('%', true) }}'"
  register: priv_result
  changed_when: false
# - name: debug priv check result
#   ansible.builtin.debug:
#     var: priv_result
- name: Add privs for {{ item.key }}
  no_log: false
  vars:
    stmt: GRANT USAGE ON `{{ item.value.name }}`.*
  when: not priv_result.stdout_lines is search(stmt)
  community.docker.docker_container_exec:
    container: mariadb
    command: mysql -u root --password={{ mysql_root_password }}
      -e "GRANT ALL PRIVILEGES ON {{ item.value.name }}.* TO {{ item.value.user }}@'{{ item.value.source | default('%', true) }}';  FLUSH PRIVILEGES;"

    # argv:
    #   - mysql
    #   - -u
    #   - root
    #   - "--password={{ mysql_root_password }}"
    #   - '-e'
    #   - "CREATE '{{ item.value.user }}'@'localhost' IDENTIFIED BY '{{ item.value.pass }}';
    #     GRANT ALL PRIVILEGES ON {{ item.value.name }} FROM '{{ item.value.user }}'@'localhost';
    #     FLUSH PRIVILEGES;"
# - name: set users
#   community.mysql.mysql_user:
#     name: "{{ item.value.user }}"
#     state: present
#     password: "{{ item.value.pass }}"
#     priv: "{{ item.value.name }}.*:ALL,GRANT"
