pgid: 911
puid: 996
tz: America/Los_Angeles
config_path: /home/archon
download_base: /srv/media/downloads
library_path: /srv/media/libraries
network: archon
mysql_password: "{{ vault_mysql_password }}"
mysql_root_password: "{{ vault_mysql_root_password }}"
mysql_user: "{{ vault_mysql_user }}"
databases: "{{ vault_databases }}"
var3: "{{ vault_var3 }}"
