---
- name: ensure dir exists
  become: true
  ansible.builtin.file:
    path: "{{ config_path }}/calibre"
    mode: 0777
    owner: "{{ puid }}"
    group: "{{ pgid }}"
    state: directory
- name: calibre
  community.docker.docker_container:
    name: calibre
    image: lscr.io/linuxserver/calibre:arch
    pull: true
    cpus: 1.0
    state: started
    restart_policy: unless-stopped
    env:
      PGUID: "{{ pgid | string }}"
      PUID: "{{ puid | string }}"
      TZ: "{{ tz }}"
      # PASSWORD: "password"
    ports:
      - 8080:8080/tcp
      - 8081:8081/tcp
    mounts:
      - source: "{{ config_path }}/calibre"
        target: /config
        type: bind
        read_only: false
      - source: "{{ library_path }}/books"
        target: /books
        type: bind
        read_only: false
      - source: "{{ download_base }}/books"
        target: /downloads
        type: bind
        read_only: false
    networks:
      - name: "{{ network }}"
