---
- name: ensure dir exists
  become: true
  ansible.builtin.file:
    path: "{{ config_path }}/radarr"
    mode: 0777
    owner: "{{ puid }}"
    group: "{{ pgid }}"
    state: directory
- name: radarr

  community.docker.docker_container:
    name: radarr
    image: lscr.io/linuxserver/radarr:latest
    state: started
    pull: true
    cpus: 1.0
    env:
      PGUID: "{{ pgid | string }}"
      PUID: "{{ puid | string }}"
      TZ: "{{ tz }}"
    ports:
      - 7878:7878/tcp
    networks:
      - name: "{{ network }}"
    mounts:
      - source: "{{ config_path }}/radarr"
        target: /config
        type: bind
        read_only: false
      - source: "{{ download_base }}"
        target: /downloads
        type: bind
        read_only: false
      - source: "{{ library_path }}"
        target: /libraries
        type: bind
        read_only: false
    restart_policy: unless-stopped
