# media_organizers/tasks/sonarr.yaml
---
- name: Ensure dir exists
  become: true
  ansible.builtin.file:
    path: "{{ config_path }}/sonarr"
    mode: 0777
    owner: "{{ puid }}"
    group: "{{ pgid }}"
    state: directory
- name: Sonarr
  community.docker.docker_container:
    name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    state: started
    cpus: 1.0
    pull: true
    env:
      PGUID: "{{ pgid | string }}"
      PUID: "{{ puid | string }}"
      TZ: "{{ tz }}"
    ports:
      - 8989:8989/tcp
    network_mode: "{{ network }}"
    networks:
      - name: "{{ network }}"
    mounts:
      - source: "{{ config_path }}/sonarr"
        target: /config
        type: bind
        read_only: false
      - source: "{{ download_base }}"
        target: /downloads
        type: bind
        read_only: false
      - source: "{{ library_path }}"
        target: /libraries
        type: bind
        read_only: false
    restart_policy: unless-stopped
