# ansible-pull setup
#
# on remote hosts, set up ansible to run periodically using the latest code
# from a particular checkout, in pull based fashion, inverting Ansible's
# usual push-based operating mode.
#
# This particular pull based mode is ideal for:
#
# (A) massive scale out
# (B) continual system remediation
#
# DO NOT RUN THIS AGAINST YOUR HOSTS WITHOUT CHANGING THE repo_url
# TO SOMETHING YOU HAVE PERSONALLY VERIFIED
#
#
---
- name: Ansible pull Setup
  become: true
  hosts: pull_mode_hosts
  remote_user: root

  vars:
    # schedule is fed directly to cron
    schedule: "*/15 * * * *"

    # User to run ansible-pull as from cron
    cron_user: root

    # File that ansible will use for logs
    logfile: /var/log/ansible-pull.log

    # Directory to where repository will be cloned
    workdir: /var/lib/ansible/local

    # Repository to check out -- YOU MUST CHANGE THIS
    # repo must contain a local.yml file at top level
    # repo_url: git://github.com/sfromm/ansible-playbooks.git
    repo_url: https://github.com/np-at/ans.git

    playbook_file: playbooks/docker.yaml
    pass_file: /root/pass
    inven_file: /etc/ansible/hosts
    # pass_file: false
  tasks:
    - name: Install ansible
      ansible.builtin.apt:
        pkg: ansible
        state: present

    - name: Create local directory to work from
      ansible.builtin.file:
        path: "{{ workdir }}"
        state: directory
        owner: root
        group: root
        mode: 0751

    # - name: Copy ansible inventory file to client
    #   ansible.builtin.copy: src=/etc/ansible/hosts dest=/etc/ansible/hosts
    #           owner=root group=root mode=0644

    # - name: Create crontab entry to clone/pull git repository
    #   ansible.builtin.template:
    #     src: templates/etc_cron.d_ansible-pull.j2
    #     dest: /etc/cron.d/ansible-pull
    #     owner: root
    #     group: root
    #     mode: 0644
    - name: Ensure Permissions on pass file
      when: pass_file
      ansible.builtin.file:
        path: "{{ pass_file }}"
        owner: root
        group: root
        mode: 0400
        state: file
    - name: Setup Cron
      ansible.builtin.cron:
        name: Ansible Pull
        cron_file: ansible-pull
        user: root
        job:
          "ansible-pull -d {{ workdir }} -U {{ repo_url }} {% if pass_file %} \
          --vault-password-file={{ pass_file }} {% endif %}{% if inven_file %}--inventory \
          {{ inven_file }}{% endif %} {{ playbook_file }} >>{{ logfile }} 2>&1"
        state: present
        minute: 15

    - name: Create logrotate entry for ansible-pull.log
      ansible.builtin.template:
        src: templates/etc_logrotate.d_ansible-pull.j2
        dest: /etc/logrotate.d/ansible-pull
        owner: root
        group: root
        mode: 0644
